apiVersion: apps/v1
kind: Deployment
metadata:
  name: graham-banano
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: graham-banano
  template:
    metadata:
      labels:
        app: graham-banano
    spec:
      containers:
      - name: graham-banano
        image: replaceme
        ports:
        - containerPort: 11337
          name: api
        command: ["/bin/bash", "-c"]
        args: ["cp /config/config.yaml .; python bot.py start_bot -p ? -u http://pippin-nano.pippin:11338 -s \"exit scam simulator\""]
        env:
          - name: REDIS_HOST
            value: redis.redis
          - name: REDIS_DB
            value: "7"
          - name: POSTGRES_HOST
            value: pg-grahambanano.graham-nano
          - name: POSTGRES_DB
            value: postgres
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: graham-banano
                key: postgres_password
          - name: BOT_TOKEN
            valueFrom:
              secretKeyRef:
                name: graham-banano
                key: bot_token
          - name: BPOW_KEY
            valueFrom:
              secretKeyRef:
                name: graham-banano
                key: bpow_key 
          - name: WALLET_ID
            valueFrom:
              secretKeyRef:
                name: graham-banano
                key: wallet_id
          - name: API_KEY
            valueFrom:
              secretKeyRef:
                name: graham-banano
                key: api_key
        volumeMounts:
        - name: conf
          mountPath: /config
          readOnly: true
      volumes:
      - name: conf
        configMap:
          name: graham-banano
          defaultMode: 0755
