apiVersion: apps/v1
kind: Deployment
metadata:
  name: grahambbet-server
  namespace: graham-banano
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: grahambbet-server
  template:
    metadata:
      labels:
        app: grahambbet-server
    spec:
      containers:
      - name: grahambbet-server
        image: replaceme
        ports:
        - containerPort: 11337
          name: api
        command: ["/bin/bash", "-c"]
        args: ["cp /config/config.yaml .; python bot.py start_server -p . -s \"rug pull simulator\" -u http://pippin-banano.pippin:11338"]
        env:
          - name: BANANO
            value: "1"
          - name: REDIS_HOST
            value: redis.redis
          - name: REDIS_DB
            value: "5"
          - name: POSTGRES_HOST
            value: pg-bbet.graham-banano
          - name: POSTGRES_DB
            value: postgres
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: graham-bbet
                key: postgres_password
          - name: BOT_TOKEN
            valueFrom:
              secretKeyRef:
                name: graham-bbet
                key: bot_token
          - name: BPOW_KEY
            valueFrom:
              secretKeyRef:
                name: graham-bbet
                key: bpow_key                
          - name: WALLET_ID
            valueFrom:
              secretKeyRef:
                name: graham-bbet
                key: wallet_id
        volumeMounts:
        - name: conf
          mountPath: /config
          readOnly: true
      volumes:
      - name: conf
        configMap:
          name: bananobot
          defaultMode: 0755
